### ISSUE TITLE
Build error: 'createFontRule' was used before it was defined.

### ISSUE THREAD

**Issue by Fantastitech** [Rise-Vision/widget-text#61]
Trying to build a completely unmodified widget-text produces the following error after the `gulp build` step:

```
/home/chris/rise/widget-text/src/widget/text.js
  line 95  col 12  'createFontRule' was used before it was defined.

✖ 1 problem

[00:30:39] 'lint' errored after 386 ms
[00:30:39] Error in plugin 'gulp-jshint'
JSHint failed for: widget/text.js
[00:30:39] 'build' errored after 414 ms
[00:30:39] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/home/chris/rise/widget-text/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/chris/rise/widget-text/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/chris/rise/widget-text/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/chris/rise/widget-text/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/home/chris/rise/widget-text/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/home/chris/rise/widget-text/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[00:30:39] Finished 'fonts' after 269 ms
[00:30:39] Finished 'i18n' after 267 ms
```

**Comment by donnapep** [comment]
No longer an issue in the latest version of the Widget.
